### Create Cart
POST http://localhost:1984/carts/fd0d777e-1a8d-46f2-8c8f-9dd8918aafd6/create-user-cart
Content-Type: application/json

{
  "userId": "14f3d786-547d-453d-8e64-4f641977f277"
}

### GET Cart
GET http://localhost:1984/carts/c248f8f2-605e-4421-aec5-dba391bea487
Content-Type: application/json

### Add Product
POST http://localhost:1984/carts/fd0d777e-1a8d-46f2-8c8f-9dd8918aafd6/add-product
Content-Type: application/json

{
  "productId": "9686c5a9-7e59-4a0c-a363-47e799acda0a",
  "productInfo": {
    "sku": "THE SKU TAL",
    "name": "Some Product",
    "price": 1234
  },
  "quantity": 1
}
### closecart
POST http://localhost:1984/carts/8507af87-e59c-49c2-9645-af6f138e05c0/close-cart

###
GET http://localhost:1984/domain
