### Create Product
POST http://localhost:1984/products/f4ee3e88-fb19-43d5-866d-447a57ef8e0f/create-product
Content-Type: application/json

{
  "sku": "THE SKU TAL",
  "name": "Some Product",
  "price": 1234,
  "quantity": 500
}

### Update Stock
POST http://localhost:1984/products/f4ee3e88-fb19-43d5-866d-447a57ef8e0f/update-stock
Content-Type: application/json

900

### get products

GET http://localhost:1984/products/f4ee3e88-fb19-43d5-866d-447a57ef8e0f
Content-Type: application/json
