### Create Product
POST http://localhost:1984/products/f4ee3e88-fb19-43d5-866d-447a57ef8e0f/create-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbWFzcnVpenIiLCJuYW1lIjoiTGEgZGF0YSBkZWwgdXNlciBxdWUgZXN0YW1vcyBhdW1lbnRhbmRvIiwiaWF0IjoxNjQyNDM3NDA1fQ._BUFnpehlZ5Y69Hr9s_DGipq0p1IP9tzRPXFTYCcJRw

{
  "sku": "THE SKU TAL",
  "name": "Some Product",
  "price": 1234,
  "quantity": 500
}

### Create Product WITH IMAGE
POST http://localhost:1984/products/dc0899af-a7b9-4090-9111-37446834f214/create-product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbWFzcnVpenIiLCJuYW1lIjoiTGEgZGF0YSBkZWwgdXNlciBxdWUgZXN0YW1vcyBhdW1lbnRhbmRvIiwiaWF0IjoxNjQyNDM3NDA1fQ._BUFnpehlZ5Y69Hr9s_DGipq0p1IP9tzRPXFTYCcJRw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="sku"

"THE SKU TAL"
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

"Some Product with image"
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="quantity"

500
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="aggregate.png"
Content-Type: image/png

< ./aggregate.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update Stock
POST http://localhost:1984/products/f4ee3e88-fb19-43d5-866d-447a57ef8e0f/update-stock
Content-Type: application/json

900

### get products

GET http://localhost:1984/products/f4ee3e88-fb19-43d5-866d-447a57ef8e0f
Content-Type: application/json
