POST http://localhost:1984/users/14f3d786-547d-453d-8e64-4f641977f277
Content-Type: application/json

{
  "name": "name",
  "lastName": "lastName",
  "mail": "mail",
  "address": "address"
}

###
GET http://localhost:1984/users/15fa71e9-786c-4a23-8ff1-2e862b96a4fb
Content-Type: application/json

###
GET http://localhost:1984/users
Content-Type: application/json

###
DELETE http://localhost:1984/users/a65c1ed9-da8a-45f2-9a8c-35daf3747b6b
Content-Type: application/json
